# Generated by Django 5.0.9 on 2024-10-06 17:40

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtail_tag_manager', '0019_cookieconsentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='wtm_include_children',
            field=models.BooleanField(default=False, help_text='Also include these tags on all children of this page.', verbose_name='Include children'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='wtm_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The tags to include when this page is loaded.', related_name='pages', to='wagtail_tag_manager.tag', verbose_name='Tags'),
        ),
    ]
